import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from utils.theme import get_chart_layout, COLORS
from utils.data_loader import format_currency

def render(df):
    if df.empty:
        return
        
    c1, c2 = st.columns([6, 4])
    
    with c1:
        st.markdown("<div class='dash-card'>", unsafe_allow_html=True)
        st.markdown("<div class='card-title'>Salesperson Performance</div>", unsafe_allow_html=True)
        st.markdown("<div class='card-subtitle'>Revenue generated by salesperson and supervisor</div>", unsafe_allow_html=True)
        
        df_sp = df.groupby(['SalespersonName', 'SupervisorName'])['SalesAmount'].sum().reset_index()
        df_sp = df_sp.sort_values('SalesAmount', ascending=True)
        
        fig_sp = px.bar(
            df_sp, x="SalesAmount", y="SalespersonName", color="SupervisorName", orientation='h',
            color_discrete_sequence=[COLORS["primary"], COLORS["orders"], COLORS["profit"], COLORS["cost"]]
        )
        fig_sp.update_traces(texttemplate='%{x:$.2s}', textposition='outside')
        layout_sp = get_chart_layout(height=450)
        layout_sp.update(
            xaxis=dict(title="Revenue ($)"), 
            yaxis=dict(title=""),
            showlegend=True, 
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1, title="Supervisor")
        )
        fig_sp.update_layout(layout_sp)
        st.plotly_chart(fig_sp, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)
        
    with c2:
        st.markdown("<div class='dash-card'>", unsafe_allow_html=True)
        st.markdown("<div class='card-title'>Revenue by Sales Channel</div>", unsafe_allow_html=True)
        st.markdown("<div class='card-subtitle'>Purchase drivers distribution</div>", unsafe_allow_html=True)
        
        df_reas = df.groupby('SalesReasonName')['SalesAmount'].sum().reset_index().sort_values('SalesAmount', ascending=True)
        
        fig_bar_reas = px.bar(
            df_reas, x="SalesAmount", y="SalesReasonName", orientation="h",
            color_discrete_sequence=[COLORS["customers"]]
        )
        fig_bar_reas.update_traces(texttemplate='%{x:$.2s}', textposition='outside')
        layout_reas = get_chart_layout(height=450)
        layout_reas.update(xaxis=dict(title="Revenue ($)"), yaxis=dict(title=""))
        fig_bar_reas.update_layout(layout_reas)
        st.plotly_chart(fig_bar_reas, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)
